### ISSUE TITLE
RequestCredentials

### ISSUE THREAD

**Issue by ZyanWlayor** [lenniezelk/shelf-cors-headers#2]
default headers "ACCESS_CONTROL_ALLOW_ORIGIN: '*'", this is disastrous for using cookies.
It is recommended to use `request.headers['origin']` instead

![图片](https://user-images.githubusercontent.com/32756492/125716090-ccdd333d-c193-4f8c-ba07-4e9c1058f2bd.png)

**Comment by lenniezelk** [comment]
This is now resolved
