### ISSUE TITLE
Improve readme example

### ISSUE THREAD

**Issue by felixblaschke** [lenniezelk/shelf-cors-headers#4]
Hi, I am the author of shelf_plus package and was looking around within the shelf package ecosystem.

Then I stumbled over your package. I looked at the readme file and found it quite hard for a first simple example. Then I looked into your implementation and found out, that your middleware is really easy to use. 

I just want to recommend to simplify the first example in the readme to something like this:
```dart
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';
import 'package:shelf_cors_headers/shelf_cors_headers.dart';

void main() async {
  var handler = const Pipeline()
      // Just add corsHeaders() middleware.
      .addMiddleware(corsHeaders())
      .addHandler(_requestHandler);

  await serve(handler, 'localhost', 8080);
}

Response _requestHandler(Request request) {
  return Response.ok('Request for "${request.url}"');
}
```
It demonstrates how easy it is. Then you can continue and show off, that you can override the headers or even use a function as an origin checker (which is huge tbh, you need to show it off :-) )

Also your cors middleware is looking neat when used along with shelf_plus:
```dart
import 'package:shelf_cors_headers/shelf_cors_headers.dart';
import 'package:shelf_plus/shelf_plus.dart';

void main() => shelfRun(init);

Handler init() {
  var app = Router().plus;

  app.use(corsHeaders());
  app.get('/', () => 'Hello World!');

  return app;
}
```
I added this to my [readme file](https://pub.dev/packages/shelf_plus#enable-cors).

**Comment by lenniezelk** [comment]
I have updated the Readme like you recommended. Thanks for mentioning this lib in your library docs. I'll be using shelf_plus next time I need a server in shelf.
