### ISSUE TITLE
Allow custom header

### ISSUE THREAD

**Issue by vanlooverenkoen** [lenniezelk/shelf-cors-headers#5]
I get an error when using a custom header

```
Request header field my-custom-header is not allowed by Access-Control-Allow-Headers in preflight response.
```

I already add `corsHeaders()` to the middleware

**Comment by lenniezelk** [comment]
Did you pass in the custom header in the corsHeaders function?
```dart
final headers = {
  'my-custom-header': 'my-value'
 };
corsHeaders(headers: headers);
```

**Comment by vanlooverenkoen** [comment]
I tried. but the `my-value` is always different. So how will that work?

**Comment by lenniezelk** [comment]
This is a bug. Will update with a fix.

**Comment by vanlooverenkoen** [comment]
`my-value` is always set by the mobile client. so it will always be different.

**Comment by lenniezelk** [comment]
I've pushed an update with the fix

**Comment by vanlooverenkoen** [comment]
NICE!

**Comment by vanlooverenkoen** [comment]
Thanks for your quick support
